### ISSUE TITLE
missing example.tsv file?

### ISSUE THREAD

**Issue by zunzun** [biosustain/croissance#2]
I cannot find a file named example.tsv in the repository, but one is mentioned in the README.rst file.  Should the repository contain this example file?

**Comment by lyschoening** [comment]
The example.tsv mentioned is just an example of how to execute the command.

**Comment by zunzun** [comment]
I understand.  Based on the graph, which is not visually a good fit at the high end, I thought I could try to fit the data to a similar but different equation.

**Comment by lyschoening** [comment]
I can try to find an example like that. Are you sure it's a bad fit though?

**Comment by lyschoening** [comment]
I believe this is the curve in the figure: [example.txt](https://github.com/biosustain/croissance/files/865956/example.txt)

**Comment by zunzun** [comment]
This is a good fit for the equation you are using; my point is that visually the graph shows the data and the plotted equation are different at both the high and low ends.  Visually it appears as if the equation has insufficient curvature for this data set.  I'm performing an equation search now to see what turns up.

**Comment by zunzun** [comment]
Search progress: see image.

![temp](https://cloud.githubusercontent.com/assets/535821/24270249/633c626e-0fe2-11e7-98db-8b7640fa3ca9.png)

**Comment by zunzun** [comment]
Incidentally, I'm using my Django curve and surface fitter for the equation search:
https://github.com/zunzun/zunzunsite3

and have a Flask curve and surface fitter here:
https://github.com/zunzun/FlaskFit

**Comment by zunzun** [comment]
Looks like an excellent candidate is a modified Janoschek growth equation as shown below.  All of what I consider good candidate equations flattened at the high end with this data set, as you see for this equation.

 w = a - (a - w0) * (1.0 - exp(-b * t^c))

    Fitting target of lowest sum of squared absolute error = 6.6812409539232860E+00

    a =  1.4058507916999551E+01
    b =  2.4291777016021242E-15
    c =  1.1111491574000036E+01
    w0 =  2.6468860631217076E+01
    
![temp](https://cloud.githubusercontent.com/assets/535821/24271390/ff14fbe8-0fe6-11e7-83f1-90ba3adc3e4d.png)

**Comment by zunzun** [comment]
That is t^c, the HTML did not paste as I expected - my apologies.
